FROM node:22-alpine

# Instala ffmpeg e dependências do sistema
RUN apk add --no-cache ffmpeg libc6-compat

# Ativa corepack (gerenciador de versão do pnpm nativo do Node)
RUN corepack enable

WORKDIR /app

# Copia arquivos de dependências
COPY package.json pnpm-lock.yaml ./

# Instala pnpm e dependências
RUN corepack prepare pnpm@10.30.3 --activate && pnpm install --frozen-lockfile

# Copia o restante do código
COPY . .

# Declara variáveis de build (passadas pelo EasyPanel via --build-arg)
ARG POSTGRES_URL
ARG AUTH_SECRET
ARG BASE_URL
ARG EVOLUTION_API_URL
ARG NEXT_PUBLIC_WEBHOOK_URL
ARG NEXT_PUBLIC_EVOLUTION_WEBHOOK_TOKEN
ARG NEXT_PUBLIC_EVOLUTION_WEBHOOK_URL
ARG PUSHER_APP_ID
ARG NEXT_PUBLIC_PUSHER_KEY
ARG PUSHER_SECRET
ARG NEXT_PUBLIC_PUSHER_CLUSTER
ARG NEXT_PUBLIC_PUSHER_HOST
ARG STRIPE_SECRET_KEY
ARG STRIPE_WEBHOOK_SECRET
ARG AUTHENTICATION_API_KEY
ARG N8N_WEBHOOK_URL

# Torna as variáveis disponíveis durante o build do Next.js
ENV POSTGRES_URL=$POSTGRES_URL
ENV AUTH_SECRET=$AUTH_SECRET
ENV BASE_URL=$BASE_URL
ENV EVOLUTION_API_URL=$EVOLUTION_API_URL
ENV NEXT_PUBLIC_WEBHOOK_URL=$NEXT_PUBLIC_WEBHOOK_URL
ENV NEXT_PUBLIC_EVOLUTION_WEBHOOK_TOKEN=$NEXT_PUBLIC_EVOLUTION_WEBHOOK_TOKEN
ENV NEXT_PUBLIC_EVOLUTION_WEBHOOK_URL=$NEXT_PUBLIC_EVOLUTION_WEBHOOK_URL
ENV PUSHER_APP_ID=$PUSHER_APP_ID
ENV NEXT_PUBLIC_PUSHER_KEY=$NEXT_PUBLIC_PUSHER_KEY
ENV PUSHER_SECRET=$PUSHER_SECRET
ENV NEXT_PUBLIC_PUSHER_CLUSTER=$NEXT_PUBLIC_PUSHER_CLUSTER
ENV NEXT_PUBLIC_PUSHER_HOST=$NEXT_PUBLIC_PUSHER_HOST
ENV STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
ENV STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET
ENV AUTHENTICATION_API_KEY=$AUTHENTICATION_API_KEY
ENV N8N_WEBHOOK_URL=$N8N_WEBHOOK_URL

# Build do Next.js
RUN pnpm build

EXPOSE 3000

ENV NODE_ENV=production
ENV PORT=3000

CMD ["node_modules/.bin/next", "start"]
